from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "login"
login_manager.login_message_category = "info"

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
mail = Mail()

def create_app():
    app = Flask(__name__)

    app.secret_key = 'secret-key'
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///database.db"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

    # Mail settings (You can also set these in environment variables)
    app.config['MAIL_SERVER'] = 'smtp.gmail.com'  # Use Gmail SMTP server
    app.config['MAIL_PORT'] = 587  # Port for TLS
    app.config['MAIL_USE_TLS'] = True  # Use TLS
    app.config['MAIL_USERNAME'] = 'farhan121921@gmail.com'  # Your Gmail address (store sensitive info in environment variables)
    app.config['MAIL_PASSWORD'] = 'oyal xmxe xdto wqab' # App-specific password generated by Google
    app.config['MAIL_DEFAULT_SENDER'] = 'farhan121921@gmail.com'

    login_manager.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    mail.init_app(app)

    return app
